"""
Unified API for DATE-SMT.

This module provides a unified interface for both bitvector and integer
approaches to DATE-SMT constraint solving.
"""

from typing import Any, Dict, List, Union

from z3 import BoolRef

from .core import Date, Period


class DateSMTBuilder:
    """Unified API for DATE-SMT constraint solving."""

    def __init__(
        self,
        approach: str = "epoch_days",
        implementation: str = "int",
        timeout_ms: int = 600000,
    ):
        """Initialize the builder with the specified approach, implementation, and timeout.

        Args:
            approach: Either "naive", "epoch_days", "hybrid", "alpha_beta", or "alpha_beta_table"
            implementation: Either "int" or "bitvector" (default: "int")
            timeout_ms: Timeout in milliseconds (default: 600000 = 10 minutes)
        """
        self.approach = approach
        self.implementation = implementation
        self.timeout_ms = timeout_ms

        # Import the appropriate solver based on implementation
        if implementation == "bitvector":
            from .symbolic_bitvector.alpha_beta_bv import AlphaBetaSolver
            from .symbolic_bitvector.alpha_beta_table_bv import AlphaBetaTableSolver
            from .symbolic_bitvector.naive_bv import NaiveSolver
            from .symbolic_bitvector.epoch_days_bv import EpochDaysSolver
            from .symbolic_bitvector.hybrid_bv import HybridSolver
        elif implementation == "int":
            from .symbolic_int.alpha_beta_int import AlphaBetaSolver
            from .symbolic_int.alpha_beta_table_int import AlphaBetaTableSolver
            from .symbolic_int.naive_int import NaiveSolver
            from .symbolic_int.epoch_days_int import EpochDaysSolver
            from .symbolic_int.hybrid_int import HybridSolver
        else:
            raise ValueError(
                f"Unknown implementation: {implementation}. Must be 'int' or 'bitvector'"
            )

        # Initialize the appropriate solver
        if approach == "naive":
            self.solver = NaiveSolver(timeout_ms=timeout_ms)
        elif approach == "epoch_days":
            self.solver = EpochDaysSolver(timeout_ms=timeout_ms)
        elif approach == "hybrid":
            self.solver = HybridSolver(timeout_ms=timeout_ms)
        elif approach == "alpha_beta":
            self.solver = AlphaBetaSolver(timeout_ms=timeout_ms)
        elif approach == "alpha_beta_table":
            self.solver = AlphaBetaTableSolver(timeout_ms=timeout_ms)
        else:
            raise ValueError(
                f"Unknown approach: {approach}. Must be 'naive', 'epoch_days', 'hybrid', 'alpha_beta', or 'alpha_beta_table'"
            )

        self.constraints = []
        self._print_smt_on_solve = False

    def add_date_var(self, name: str) -> "DateVar":
        """Add a symbolic date variable."""
        return self.solver.add_date_var(name)

    def add_constraint(self, constraint: Any, description: str = "") -> None:
        """Add a constraint to the solver.

        Accepts both Z3 BoolRef (for symbolic solvers) and ConstraintWrapper
        (for enumeration baseline).
        """
        if description:
            print(f"Added constraint: {description}")
        # Guard against None constraints
        if constraint is None:
            raise TypeError(
                "Constraint is None. Ensure expressions return a valid constraint."
            )
        self.constraints.append(constraint)
        self.solver.add_constraint(constraint)

    def solve(self) -> Dict[str, Any]:
        """Solve the constraints and return results."""
        if self._print_smt_on_solve:
            print("\n; SMT-LIB dump (generated by DATE-SMT)")
            print(self.to_smt2())
        result = self.solver.solve()
        if result["status"] == "sat":
            print(f"✅ SATISFIABLE:")
            for name, date in result["dates"].items():
                print(f"  {name} = {date}")
        else:
            print("❌ UNSATISFIABLE")
        return result

    def get_constraints(self) -> List[BoolRef]:
        """Get all constraints."""
        return self.constraints

    def to_smt2(self) -> str:
        """Return the current problem in SMT-LIB v2 format."""
        return self.solver.to_smt2()

    def enable_smtlib_print(self, enabled: bool = True) -> None:
        """Enable or disable printing SMT-LIB when solving."""
        self._print_smt_on_solve = enabled
