"""
Unified API for DATE-SMT constraint solving.

This module provides a unified interface for both baseline and advanced
approaches to DATE-SMT constraint solving.
"""

from typing import Any, Dict, List, Union

from z3 import BoolRef

from .core import Date, Period
from .symbolic_advanced import AdvancedDateSolver
from .symbolic_baseline import DateSolver
from .symbolic_hybrid import HybridDateSolver
from .symbolic_ab import AbDateSolver


class DateSMTBuilder:
    """Unified API for DATE-SMT constraint solving."""

    def __init__(self, approach: str = "advanced", timeout_ms: int = 60000):
        """Initialize the builder with the specified approach and timeout.

        Args:
            approach: Either "baseline", "advanced", or "hybrid"
            timeout_ms: Timeout in milliseconds (default: 60 seconds)
        """
        self.approach = approach
        if approach == "baseline":
            self.solver = DateSolver(timeout_ms=timeout_ms)
        elif approach == "advanced":
            self.solver = AdvancedDateSolver(timeout_ms=timeout_ms)
        elif approach == "hybrid":
            self.solver = HybridDateSolver(timeout_ms=timeout_ms)
        elif approach == "ab":
            self.solver = AbDateSolver(timeout_ms=timeout_ms)
        else:
            raise ValueError(
                f"Unknown approach: {approach}. Must be 'baseline', 'advanced', 'hybrid', or 'ab'"
            )

        self.constraints = []
        self._print_smt_on_solve = True
        self.timeout_ms = timeout_ms

    def add_date_var(self, name: str):
        """Add a symbolic date variable."""
        return self.solver.add_date_var(name)

    def add_period_var(self, name: str):
        """Add a symbolic period variable."""
        return self.solver.add_period_var(name)

    def add_constraint(self, constraint: BoolRef, description: str = ""):
        """Add a constraint to the solver."""
        if description:
            print(f"Added constraint: {description}")
        # Guard against None or non-bool constraints
        if constraint is None:
            raise TypeError("Constraint is None. Ensure expressions return a Z3 BoolRef.")
        self.constraints.append(constraint)
        self.solver.add_constraint(constraint)

    def solve(self) -> Dict[str, Any]:
        """Solve the constraints and return results."""
        if self._print_smt_on_solve:
            print("\n; SMT-LIB dump (generated by DATE-SMT)")
            print(self.to_smt2())
        result = self.solver.solve()
        if result['status'] == 'sat':
            print(f"✅ Solution found:")
            for name, date in result['dates'].items():
                print(f"  {name} = {date}")
            if result.get('periods'):
                for name, period in result['periods'].items():
                    print(f"  {name} = {period}")
        else:
            print("❌ No solution found")
        return result

    def get_constraints(self) -> List[BoolRef]:
        """Get all constraints."""
        return self.constraints

    def enable_smtlib_print(self, enabled: bool = True):
        """Enable or disable printing SMT-LIB when solving."""
        self._print_smt_on_solve = enabled

    def to_smt2(self) -> str:
        """Return the current solver state as SMT-LIB v2 string."""
        return self.solver.to_smt2()
